name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/btn_tongyong_n.jpg
    - images/btn_tongyong_p.jpg
    - images/ic_about.png
    - images/ic_account_normal.png
    - images/ic_back.png
    - images/ic_book_normal.png
    - images/ic_book_selected.png
    - images/ic_check_box_checked.png
    - images/ic_check_box_unchecked.png
    - images/ic_close.png
    - images/ic_coin.png
    - images/ic_collect.png
    - images/ic_delete.png
    - images/ic_empty.png
    - images/ic_error.png
    - images/ic_eye_normal.png
    - images/ic_favorite.png
    - images/ic_github.png
    - images/ic_heart.png
    - images/ic_home_normal.png
    - images/ic_home_selected.png
    - images/ic_jianshu.png
    - images/ic_launcher_foreground.png
    - images/ic_launcher_round.png
    - images/ic_mine_normal.png
    - images/ic_mine_selected.png
    - images/ic_more.png
    - images/ic_next.png
    - images/ic_password_normal.png
    - images/ic_project_normal.png
    - images/ic_project_selected.png
    - images/ic_qq.png
    - images/ic_qq_group.png
    - images/ic_rank.png
    - images/ic_rank_1.png
    - images/ic_rank_2.png
    - images/ic_rank_3.png
    - images/ic_read_later.png
    - images/ic_rule.png
    - images/ic_search.png
    - images/ic_setting.png
    - images/ic_wechat_normal.png
    - images/ic_wechat_selected.png
    - images/image_holder.png
    - images/img_book.png
    - images/img_github.png
    - images/img_heart.png
    - images/img_right.png
    - images/img_setting.png
    - images/img_star.png
    - images/img_user_head.png
    - images/login_bg.png
    - images/logo.png
    - images/pic_404.jpg
    - images/zan_0.png
    - images/zan_1.png
    - images/list_icon_gas.png
    - images/snow.png
    - images/test.png
    - images/test2.png
    - images/tab_icon_discover.png
    - images/tab_icon_discover_active.png
    - images/tab_icon_my.png
    - images/tab_icon_my_active.png
    - images/tab_icon_news.png
    - images/tab_icon_news_active.png
    - images/n1.jpeg
    - images/n2.jpg
    - images/n3.jpg
    - images/n4.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
